CONFIG_STACK_SENTINEL=y
CONFIG_STACK_CANARIES=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_MONITOR=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Enable Fault Tolerance Subsystem
CONFIG_FAULT_TOLERANCE=y
CONFIG_FAULT_TOLERANCE_AUTO_INIT=y
CONFIG_FT_ENABLE_STACK_OVERFLOW_PROTECTION=y
CONFIG_FT_STACK_OVERFLOW_THRESHOLD=128
CONFIG_FAULT_TOLERANCE_MONITOR_STACK_SIZE=2048
CONFIG_FAULT_TOLERANCE_RECOVER_STACK_SIZE=2048
CONFIG_FT_MSG_QUEUE_SIZE=10
