# Configuration for Fault Tolerance API Testing Application
# ECE753 Project - Enhanced Fault Tolerance in Zephyr RTOS
# Author: Jack Ostapeic, MS ECE student at UW-Madison

# enable fault tolerance framework
CONFIG_FAULT_TOLERANCE=y
CONFIG_FAULT_TOLERANCE_AUTO_INIT=y
CONFIG_FAULT_TOLERANCE_INIT_PRIORITY=60
CONFIG_FT_ENABLE_STACK_OVERFLOW_PROTECTION=y

CONFIG_STACK_SENTINEL=y
CONFIG_STACK_CANARIES=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_MONITOR=y
CONFIG_MAIN_STACK_SIZE=1024
CONFIG_BOOT_BANNER=y



# enable logging and console output
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

