# Configuration for Jack Testing Fault Tolerance Application
# ECE753 Project - Enhanced Fault Tolerance in Zephyr RTOS
# Author: Jack Ostapeic, MS ECE student at UW-Madison

# enable fault tolerance framework
CONFIG_FAULT_TOLERANCE=y
CONFIG_FAULT_TOLERANCE_AUTO_INIT=y
CONFIG_FAULT_TOLERANCE_INIT_PRIORITY=60

CONFIG_STACK_SENTINEL=y
CONFIG_STACK_CANARIES=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_NAME=y
CONFIG_MULTITHREADING=y
CONFIG_THREAD_ANALYZER=y